print("Welcome to python world")
a=eval(input("Enter a number"))
b=eval(input("Enter 2nd number"))
print("Sum is",a+b)
print("Difference is",a-b)
print("Product is",a*b)
print("Division is",a/b)
print("Floor division is",a//b)
print("Remainder is",a%b)
